### ISSUE TITLE
npm install error on 1.0.3

### ISSUE THREAD

**Issue by sjmueller** [olofd/react-native-photos-framework#46]
`Failed at the react-native-photos-framework@1.0.3 postinstall script 'node install.js'`

I am on OSX, using homebrew nvm:
```
❯ node --version
v7.9.0
```

**Comment by sjmueller** [comment]
Stack trace:
```
96335 verbose stack Exit status 1
96335 verbose stack     at EventEmitter.<anonymous> (.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
96335 verbose stack     at emitTwo (events.js:106:13)
96335 verbose stack     at EventEmitter.emit (events.js:194:7)
96335 verbose stack     at ChildProcess.<anonymous> (.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
96335 verbose stack     at emitTwo (events.js:106:13)
96335 verbose stack     at ChildProcess.emit (events.js:194:7)
96335 verbose stack     at maybeClose (internal/child_process.js:899:16)
96335 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by sjmueller** [comment]
Ok got to the root of this one. I recently tried to use react native cli upgrade option, and because our xcode project is named differently than the repo, it created a bunch of empty project files inside of the `ios` directory. Then when the postinstall script tried to figure out the project name, apparently these files misled react native's `getProjectName` function which lead to this error:
`Error: ENOENT: no such file or directory, open '/ios/wrong-project-name.xcodeproj/project.pbxproj'

Removing the dead files fixed everything.
