### ISSUE TITLE
Error: Cannot find module 'plist'

### ISSUE THREAD

**Issue by tommynordli** [olofd/react-native-photos-framework#92]
When trying to install I'm getting this error during postinstall

Xcode v10.0
react-native v0.57.1

```
$ npm i --save react-native-photos-framework

> react-native-photos-framework@1.0.8 postinstall /Users/tommy/Git/noisolation/FamilyFrame/node_modules/react-native-photos-framework
> node install.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'plist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tommy/Git/noisolation/FamilyFrame/node_modules/react-native-photos-framework/local-cli/link/ios/copyAssets.js:5:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-photos-framework@1.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-photos-framework@1.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tommynordli** [comment]
`$ npm i --save --ignore-scripts react-native-photos-framework` 

Ignoring scripts did the job for now, as the problem was in the postinstall script, whos only job was to add NSPhotoLibraryUsageDescription to the plist, which I don't think it should do anyway.
