### ISSUE TITLE
Error on install: Attempt to change mapping for "otf" extension from "font/otf" to "font/opentype".

### ISSUE THREAD

**Issue by indapublic** [olofd/react-native-photos-framework#94]
> node -v
v8.12.0

> yarn -v
1.12.3

I see error while installing.

`yarn add react-native-photos-framework`

> error /path/to/project/node_modules/react-native-photos-framework: Command failed.
> Exit code: 1
> Command: node install.js
> Arguments:
> Directory: /path/to/project/node_modules/react-native-photos-framework
> Output:
> /path/to/project/node_modules/mime/Mime.js:48
>         throw new Error(
>         ^
> 
> Error: Attempt to change mapping for "otf" extension from "font/otf" to "font/opentype". Pass `force=true` to allow this, otherwise remove "otf" from the list of extensions for "font/opentype".
>     at Mime.define (/path/to/project/node_modules/mime/Mime.js:48:15)
>     at Object.<anonymous> (/path/to/project/node_modules/react-native-photos-framework/local-cli/link/groupFilesByType.js:9:6)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)

**Comment by tvpranav** [comment]
@jochem725  Still getting this issue while installing library in react-native 0.61.4. Could you please help me to get out of this issue?
Also having this library in my project -> 
"react-native-video": "git://github.com/olofd/react-native-video.git#react-native-photos-framework"
